### ISSUE TITLE
Notification sound is going thru speaker

### ISSUE THREAD

**Issue by skamlet** [adrcotfas/Goodtime#66] opened 2017-04-11 13:53 UTC
There's a sound notification thru the speaker even though headphones are plugged in and notification sound is set to "Silent" in the settings.
The device is also set as prioritary notifications only (Goodtime is not set as prioritary) and it also still pass thru the speaker.

It would be great to have other way to be notified when working with people around you that you don't want to disturb.

Any ideas of why this is happening?

**Comment by adrcotfas** [comment] 2017-04-11 13:57
This is a duplicate of #25 
It will be fixed in future versions.

**Closed by adrcotfas** 2017-04-11 13:57 UTC
