### ISSUE TITLE
Break finished, Start work popup after Work session just finished

### ISSUE THREAD

**Issue by ngleb** [adrcotfas/Goodtime#193] opened 2020-05-14 08:42 UTC
I have a really weird behaviour. Android 8,  Goodtime 2.1.13 from F-Droid, fresh settings (all data was removed before reproducing the problem).

I have setup a test profile with 1 minute work session, 1 minute break, 1 minute long break and 4 sessions before the long break happens.

1) Start work session, lock the screen,
2) Work session finished. Goodtime popup appears stating that "Break finished, Start work?". Android notification is correct in this case, but still sometime it disappears.

Another bug I have is the following:

1) Start work session, lock the screen,
2) Work session finished. Goodtime popup appears stating that "Break finished, Start work?". I ignore this popup as it is incorrect and start break from Android notification.
3) Then I go to the app and popup notification is still there in the app offering me to start work (but I just started a break from the Notification area).

**Comment by adrcotfas** [comment] 2020-05-14 13:42
For the first situation, do you mean the dialog or the notification? When does it dissapear, after you see it on the screen?

For the second situation, I received similar feedback from another user. I cannot reproduce this but have an idea. A possible fix will come in 2.1.14 today (it may take a while to reach F-Droid though).

**Comment by ngleb** [comment] 2020-05-14 15:08
My phone is Motorola Moto G5S+ with stock ROM, so I did another test. Motorola phones has a feature called Moto Display (Display Peek) which changes how lock screen works. So basically lock screen itself is not changed, but there's another thing that turns the screen on when phone is moved or there's a notification, to show notifications and time.

I disabled Moto Display completely and did another test. This time Goodtime much better, but I still saw old popups in the app. I'll try to do more tests and provide more detailed description of the problem. I know how tough can it be to fix bug on different phones.

Here's one to reproduce the issue with stuck popup in the app when it should not be shown (this is with Moto Display disabled).
1) Before the start, I reset session counter and killed the app.
2) Start Goodtime
3) Start Work Session
4) Press Home button to return to home screen
5) Press Power button to turn the screen off and lock it
6) Wait until Work Session is finished. Dialogue / popup with text "Session finished" appears
7) Do not press Start break, but instead press Home button. Screen returns to Lock screen
8) Unlock screen
9) Go to Notification panel and press "Start break" from Goodtime Notification
10) Go to Notification panel again and press on it to open Goodtime. At this point I can see that Break is in progress
11) Press Home button to return to Home screen
12) Open Notification panel and press on Goodtime notification again. Goodtime app opens, Break is still in progress
13) No dialogue / popup should appear at this point, however I see "Session finished" while Break is still in progress.

At step 7 it is expected that a user should press "Start break", but as I have described in the first message I often see a wrong dialogue which says that "Break finished", while Notification says that "Session finished".

**Comment by adrcotfas** [comment] 2020-05-14 18:47
Thanks a lot! I managed to reproduce it on my device. I'll find a fix ASAP.

**Comment by adrcotfas** [comment] 2020-05-14 21:03
This was fixed in 2.1.14.

**Closed by adrcotfas** 2020-05-14 21:03 UTC
